version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: memegiphy_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memegiphy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey123  # В продакшене вынести в .env
    volumes:
      - meili_data:/meili_data
    networks:
      - app-network

  bot:
    build: ./telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BACKEND_URL=http://backend:8000/api/v1
      # ЗАМЕНИТЕ НА ВАШ NGROK URL ИЛИ ПУБЛИЧНЫЙ IP ДЛЯ ТЕСТА:
      - BASE_MEDIA_URL=https://ВАШ-URL.ngrok-free.app 
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  meili_data:

networks:
  app-network:
    driver: bridge